#Nom du workflow
name: push workflow
#Trigger
on: push
#Les actions à faire
jobs: 

    first-job: 
        name: Build 
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up JDS 17
              uses: actions/setup-java@v3
            - name: Install maven dependencies
              run: mvn install -DskipTests
            - name: Build maven
              run: mvn package