#Nom du workflow
name: push workflow
#Trigger
on: push
#Les actions à faire
jobs: 
    build: 
        name: Build et run
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up JDS 17
              uses: actions/setup-java@v4
              with: 
                distribution: 'temurin'
                java-version: '17'
            - name: Cache Maven 
              uses: actions/cache@v4
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                  ${{ runner.os }}-maven-
            - name: Install maven dependencies
              run: mvn install -DskipTests
            - name: Build maven
              run: mvn package
            - name: Upload du build
              uses: actions/upload-artifact@v4
              with:
                name: Build-artifact
                path: target/*.jar

    display:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Récupérer l'artéfact
          uses: actions/download-artifact@v4
          with:
            name: Build-artifact
        - name: lister les fichiers
          run: ls